# Generated by Django 2.2.3 on 2019-07-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='nome',
            new_name='nome_do_arquivo',
        ),
    ]
