# Generated by Django 2.2.3 on 2019-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0002_auto_20190705_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='nome_do_arquivo',
            field=models.CharField(help_text='.mp3', max_length=255),
        ),
    ]
