# Generated by Django 2.2.3 on 2019-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0003_auto_20190705_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='idioma_do_texto',
            field=models.CharField(choices=[('1', 'Português'), ('2', 'English')], default=('1', 'Português'), max_length=15),
        ),
    ]
