# Generated by Django 2.2.3 on 2019-07-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0005_auto_20190705_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='idioma_do_texto',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en-us', 'English'), ('es', 'Espanol')], default=('pt-br', 'Português'), max_length=15),
        ),
    ]
