# Generated by Django 2.2.3 on 2019-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0006_auto_20190705_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='idioma_do_texto',
            field=models.CharField(choices=[('pt-br', 'Português (BR)'), ('pt-pt', 'Português (PT)'), ('en-us', 'Inglês (EUA)'), ('es', 'Espanhol')], default=('pt-br', 'Português'), max_length=15),
        ),
    ]
