# Generated by Django 2.2.3 on 2019-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0007_auto_20190705_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='nome_do_arquivo',
            field=models.CharField(max_length=255),
        ),
    ]
