# Generated by Django 2.2.3 on 2019-07-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversor', '0013_auto_20190708_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='nome_do_arquivo',
        ),
        migrations.AddField(
            model_name='audio',
            name='nome',
            field=models.CharField(db_column='Nome do arquivo', default='', help_text='Não utilize acento no nome do arquivo.', max_length=255),
        ),
    ]
